// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CountDown: typeof import('./src/components/CountDown/index.vue')['default']
    HeaderBack: typeof import('./src/components/header/HeaderBack/index.vue')['default']
    List: typeof import('./src/components/list/index.vue')['default']
    ListView: typeof import('./src/components/list/listView.vue')['default']
    ListView1: typeof import('./src/components/list/listView1.vue')['default']
    Main: typeof import('./src/components/Main/index.vue')['default']
    PopupBuy: typeof import('./src/components/popup/popup-buy.vue')['default']
    PopupLoginOut: typeof import('./src/components/popup/popup-loginOut.vue')['default']
    PopupMenu: typeof import('./src/components/popup/popup-menu.vue')['default']
    PopupPayNow: typeof import('./src/components/popup/popup-payNow.vue')['default']
    PopupQuickJoin: typeof import('./src/components/popup/popup-quickJoin.vue')['default']
    PopupRecharge: typeof import('./src/components/popup/popup-recharge.vue')['default']
    PopupRegister: typeof import('./src/components/popup/popup-register.vue')['default']
    PopupTip: typeof import('./src/components/popup/popup-tip.vue')['default']
    PopupTopClaim: typeof import('./src/components/popup/popup-topClaim.vue')['default']
    Progress: typeof import('./src/components/Progress/index.vue')['default']
    Qr: typeof import('./src/components/qr/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VBack: typeof import('./src/components/header/v-back.vue')['default']
    VFooter: typeof import('./src/components/footer/v-footer.vue')['default']
    VHeader: typeof import('./src/components/header/v-header.vue')['default']
  }
}
